language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
script: npm run $COMMAND
env:
  - COMMAND=lint
  - COMMAND=test
  - COMMAND=test:karma
  - COMMAND=integration MR_VERSION=. MOP_VERSION=latest
  - COMMAND=integration MR_VERSION=. MOP_VERSION="#master"
notifications:
  irc:
    channels:
      - "chat.freenode.net#montage"
    on_success: false
    template:
      - "%{author} broke the %{repository} tests on %{branch}: %{build_url}"
deploy:
    provider: npm
    email: "${NPM_EMAIL}"
    api_key: "${NPM_API_KEY}"
    on:
        tags: true
