language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
jobs:
    include:
      - stage: lint
        node_js: 8
        script: npm run lint
      - stage: test
        script: npm run $COMMAND
        env:
        - COMMAND=test
        - COMMAND=test:karma
        - COMMAND=integration MR_VERSION=. MOP_VERSION=latest
        - COMMAND=integration MR_VERSION=. MOP_VERSION="#master"
      - stage: deploy
        script: skip
        deploy:
            provider: npm
            email: "${NPM_EMAIL}"
            api_key: "${NPM_API_KEY}"
            on:
                tags: true
notifications:
  irc:
    channels:
      - "chat.freenode.net#montage"
    on_success: false
    template:
      - "%{author} broke the %{repository} tests on %{branch}: %{build_url}"
